# Check the code coverage. The results are published at
# <https://app.codecov.io/gh/terminusdb/terminusdb-store>.
name: Code coverage

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install nightly toolchain
      run: |
        rustup toolchain install nightly --component llvm-tools-preview
        rustup override set nightly

    - name: Check code coverage
      run: bash ci/linux_build.sh
