# Check the code coverage.
name: Code coverage

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install nightly toolchain
      run: |
        rustup toolchain install nightly --component llvm-tools-preview
        rustup override set nightly

    - name: Install grcov
      run: cargo install grcov

    - name: Build with coverage instrumentation
      env:
        CARGO_INCREMENTAL: "0"
        RUSTFLAGS: "-Cinstrument-coverage"
      run: cargo build --verbose

    - name: Run tests with coverage
      env:
        CARGO_INCREMENTAL: "0"
        RUSTFLAGS: "-Cinstrument-coverage"
        LLVM_PROFILE_FILE: "terminus-%p-%m.profraw"
      run: cargo test --verbose

    - name: Generate coverage report
      run: |
        grcov . -s . --binary-path ./target/debug/ -t lcov --branch \
          --ignore-not-existing --ignore "/*" -o lcov.info

    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        files: lcov.info
        fail_ci_if_error: false
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
